### ISSUE TITLE
ADS pages not rendering correctly due to markdown files changes

### ISSUE THREAD

**Issue by ryan-aus** [wagov/wasocshared#483]
Changes made to ADS markdown files has affected how ADS files are formatted on the SOC public site

![image](https://github.com/wagov/wasocshared/assets/58383101/9b9d02b5-8543-4d70-b7c8-37009fa7d709)

Related to commit [ddbcedb](https://github.com/wagov/wasocshared/commit/ddbcedbb8243175ed31696f0de55e789e3e98dc4)

**Comment by DGovEnterprise** [comment]
@adonm to review

**Comment by adonm** [comment]
Have updated template to use admonitions better, ADS's can move over to new styling to fix
